### ISSUE TITLE
Spacing issue between headers and paragraphs

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguides-common#114]
The spacing between the headers and paragraphs make the content confusing. Some of the headers are closer to the previous text than the following text, and inconsistent spacing for h4 headers.

![image](https://user-images.githubusercontent.com/689163/36912152-7ae993fe-1e0b-11e8-9ff6-4b6d5ec45147.png)

This will require fixes in openliberty.io repo, iguides-common, and all the interactive guide repos:
- [x] openliberty.io repo (OpenLiberty/openliberty.io#180)
- [x] iguides-common (#115)
- [x] iguide-circuitbreaker (Openliberty/iguide-circuit-breaker#96)
- [x] iguide-bulkhead (OpenLiberty/draft-iguide-bulkhead#89)
- [x] iguide-microprofile-config (OpenLiberty/iguide-microprofile-config#158)
