### ISSUE TITLE
[Ongoing] Checklist for interactive guides multi-pane conversion

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#162]
This checklist provides a guide on what needs to be done for each existing interactive guide in order to convert it to the new multipane layout.

- [ ] In \<guide>.html
- Change the layout from 'interactive-guide' to 'iguide-multipane'
- Remove `interactive-guides/table-of-contents` from the CSS listing
- Add `interactive-guides/iguide-multipane` under the JS imports
- Add `categories: MicroProfile`

- [ ] In \<guide>.js
- Remove `$(ID.toc_guide_title).hide();`  statement.    See circuit-breaker-guide.js.

- [ ] in \<guide>.json
- In instructions, remove bold tags (\<b>...\<b>) in action tags.   The actions are no longer bolded.  Bolding is reserved for referring to other parameter values in text and to highlight a button name in an instruction which is not part of an action tag.
- Add a \<br> tag, if needed, following all code insertion tags in the instructions so the code to be inserted falls on its own line.  The phrases beginning with 'Then, click...' should consistently appear on their own line.
- Move the instruction entry for the playground step that appears in the step's **description** array to be its own entry in the step's **instruction** array.   It had appeared in the **description** array prefaced with '\<instruction class='playgroundInstructionStyle' tabindex='0'>' so that it would be styled like an instruction but not be used to activate the **Next** button.   Now we just want it to appear as an instruction.
- Remove any **NOSHOW** instruction entries.
- Add a "writeable" attribute for any content editor that has code insert/edit to show the writable section with left green border color. See circuit-breaker.json
- Add "defaultWidgets" stanza to the guide data at the top. This shows the default widgets to be created for steps at begining that don't have any widgets. The defaultWidgets would show the default content of the first widget that we'll use in the step.
- For each guide step AND section, go through and add in the widgets that display on the right hand side of a multi-column format, but that are disabled.  Identify these widges as "enable": false.  See circuit-breaker.json.
- Specifying that the order in the JSON file must always be browser, pod, editor.  This order can be altered in single column view using the 'singleColumnOrder' setting in the JSON file.  See the bulkhead guide for its use.
- Add configWidgets section to the JSON file. This is to specify the widgets height for the browser, pod, and the maximum or full length of the editor.   If you need the browser to be a different height in single column mode, you can specify 'singleColumnHeight' in the JSON file.  This was used in the bulkhead guide to show the browser content without scrolling.
- New widget flags in the JSON:
       enable: the widgets that are use in this step  (`"enable":false)`
       active: the active one that will be interact first in this step   (`"active": true`)
       hidden: the widget is not show when initially display the step
       height: to override the configured height, eg. "height": "300px"
       singleColumnOrder: the ordering of the widget in the single column view 
             This ordering will not be applied to multi column view. Once one widget in the step has singleColumnOrder attribute, other widgets in the same step have to provide this attribute too, eg.

             {"displayType": "webBrowser", "singleColumnOrder": "3", ...}
             {"displayType": "pod",  "singleColumnOrder": "2", ...}
             {"displayType": "TabbedEditor",  "singleColumnOrder": "1", ...}

- Consistently make all Editor action buttons 'Run' or 'Save', but do not flop between them.  The 'Run' action is to stand for saving a change, building, and deploying and should most likely be used in most guides.  **Awaiting customer feedback** on this item.  Also make sure that all editors in the tabbed editor have the same button across the top.
- Once a file is open in an editor, it should appear as READONLY in all subsequent tabbed editors.  For example, once enabling the feature in the server.xml, all subsequent tabbed editors should have a server.xml tab.

- [ ] in \<guide>-callback.js
- Remove calls to:
contentManager.updateWithNewInstructionNoMarkComplete()
contentManager.updateWithNewInstruction()
contentManager.addCheckmarkToInstruction()
contentManager.markInstructionDisable()

- Use stepContent.resizeStepWidgets(....) in the callback methods to add focus to a widget in the right column of the multipane layout so that it grows to the proper height to be more visible.   Another alternative to bringing a widget into focus is to trigger a click even on the widget.  For example: 
`webBrowser.contentRootElement.trigger("click");`

- [ ] Update sample app with any changes to the .html and .css files within.  Update the .zip that contains the sample app too.

- [ ] End of the guide section

- Move 'Download the sample xxx application on github link' on the left to the right under 'Where to next?' section by remove the Download link in the WhatNext step in the .json's description section
- Add `categories: MicroProfile` in the guidename-guide.html
- Add a link below related guides for the following:
    Learn more about MicroProfile.
    See the MicroProfile specs.
    View MicroProfile API.
for example by adding this section to the .json:
{
            "name": "RelatedLinks",
            "title": "Related links",
            "description": ["Learn more about <b>MicroProfile</b>.",
                            `<p> <a target='_blank' rel='noopener noreferrer' href='http://microprofile.io/' >See the MicroProfile specs.</a></p>`,
                            `<p> <a target='_blank' rel='noopener noreferrer' href='https://openliberty.io/docs/ref/microprofile/' >View MicroProfile API.</a></p>`
                                    ]
}
